# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Joel/Desktop/Margarita

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Joel/Desktop/Margarita

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Joel/Desktop/Margarita/CMakeFiles /mnt/c/Users/Joel/Desktop/Margarita/Margarita/CMakeFiles/progress.marks
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f CMakeFiles/Makefile2 Margarita/all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Joel/Desktop/Margarita/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f CMakeFiles/Makefile2 Margarita/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f CMakeFiles/Makefile2 Margarita/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f CMakeFiles/Makefile2 Margarita/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
Margarita/CMakeFiles/Margarita.dir/rule:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f CMakeFiles/Makefile2 Margarita/CMakeFiles/Margarita.dir/rule
.PHONY : Margarita/CMakeFiles/Margarita.dir/rule

# Convenience name for target.
Margarita: Margarita/CMakeFiles/Margarita.dir/rule

.PHONY : Margarita

# fast build rule for target.
Margarita/fast:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/build
.PHONY : Margarita/fast

AirStrike.o: AirStrike.cpp.o

.PHONY : AirStrike.o

# target to build an object file
AirStrike.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/AirStrike.cpp.o
.PHONY : AirStrike.cpp.o

AirStrike.i: AirStrike.cpp.i

.PHONY : AirStrike.i

# target to preprocess a source file
AirStrike.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/AirStrike.cpp.i
.PHONY : AirStrike.cpp.i

AirStrike.s: AirStrike.cpp.s

.PHONY : AirStrike.s

# target to generate assembly for a file
AirStrike.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/AirStrike.cpp.s
.PHONY : AirStrike.cpp.s

Animation.o: Animation.cpp.o

.PHONY : Animation.o

# target to build an object file
Animation.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Animation.cpp.o
.PHONY : Animation.cpp.o

Animation.i: Animation.cpp.i

.PHONY : Animation.i

# target to preprocess a source file
Animation.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Animation.cpp.i
.PHONY : Animation.cpp.i

Animation.s: Animation.cpp.s

.PHONY : Animation.s

# target to generate assembly for a file
Animation.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Animation.cpp.s
.PHONY : Animation.cpp.s

Block.o: Block.cpp.o

.PHONY : Block.o

# target to build an object file
Block.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Block.cpp.o
.PHONY : Block.cpp.o

Block.i: Block.cpp.i

.PHONY : Block.i

# target to preprocess a source file
Block.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Block.cpp.i
.PHONY : Block.cpp.i

Block.s: Block.cpp.s

.PHONY : Block.s

# target to generate assembly for a file
Block.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Block.cpp.s
.PHONY : Block.cpp.s

Bomb.o: Bomb.cpp.o

.PHONY : Bomb.o

# target to build an object file
Bomb.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Bomb.cpp.o
.PHONY : Bomb.cpp.o

Bomb.i: Bomb.cpp.i

.PHONY : Bomb.i

# target to preprocess a source file
Bomb.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Bomb.cpp.i
.PHONY : Bomb.cpp.i

Bomb.s: Bomb.cpp.s

.PHONY : Bomb.s

# target to generate assembly for a file
Bomb.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Bomb.cpp.s
.PHONY : Bomb.cpp.s

BombAnimation.o: BombAnimation.cpp.o

.PHONY : BombAnimation.o

# target to build an object file
BombAnimation.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/BombAnimation.cpp.o
.PHONY : BombAnimation.cpp.o

BombAnimation.i: BombAnimation.cpp.i

.PHONY : BombAnimation.i

# target to preprocess a source file
BombAnimation.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/BombAnimation.cpp.i
.PHONY : BombAnimation.cpp.i

BombAnimation.s: BombAnimation.cpp.s

.PHONY : BombAnimation.s

# target to generate assembly for a file
BombAnimation.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/BombAnimation.cpp.s
.PHONY : BombAnimation.cpp.s

Coin.o: Coin.cpp.o

.PHONY : Coin.o

# target to build an object file
Coin.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Coin.cpp.o
.PHONY : Coin.cpp.o

Coin.i: Coin.cpp.i

.PHONY : Coin.i

# target to preprocess a source file
Coin.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Coin.cpp.i
.PHONY : Coin.cpp.i

Coin.s: Coin.cpp.s

.PHONY : Coin.s

# target to generate assembly for a file
Coin.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Coin.cpp.s
.PHONY : Coin.cpp.s

Comet.o: Comet.cpp.o

.PHONY : Comet.o

# target to build an object file
Comet.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Comet.cpp.o
.PHONY : Comet.cpp.o

Comet.i: Comet.cpp.i

.PHONY : Comet.i

# target to preprocess a source file
Comet.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Comet.cpp.i
.PHONY : Comet.cpp.i

Comet.s: Comet.cpp.s

.PHONY : Comet.s

# target to generate assembly for a file
Comet.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Comet.cpp.s
.PHONY : Comet.cpp.s

ControlManager.o: ControlManager.cpp.o

.PHONY : ControlManager.o

# target to build an object file
ControlManager.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/ControlManager.cpp.o
.PHONY : ControlManager.cpp.o

ControlManager.i: ControlManager.cpp.i

.PHONY : ControlManager.i

# target to preprocess a source file
ControlManager.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/ControlManager.cpp.i
.PHONY : ControlManager.cpp.i

ControlManager.s: ControlManager.cpp.s

.PHONY : ControlManager.s

# target to generate assembly for a file
ControlManager.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/ControlManager.cpp.s
.PHONY : ControlManager.cpp.s

ControlsScreen.o: ControlsScreen.cpp.o

.PHONY : ControlsScreen.o

# target to build an object file
ControlsScreen.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/ControlsScreen.cpp.o
.PHONY : ControlsScreen.cpp.o

ControlsScreen.i: ControlsScreen.cpp.i

.PHONY : ControlsScreen.i

# target to preprocess a source file
ControlsScreen.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/ControlsScreen.cpp.i
.PHONY : ControlsScreen.cpp.i

ControlsScreen.s: ControlsScreen.cpp.s

.PHONY : ControlsScreen.s

# target to generate assembly for a file
ControlsScreen.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/ControlsScreen.cpp.s
.PHONY : ControlsScreen.cpp.s

Crab.o: Crab.cpp.o

.PHONY : Crab.o

# target to build an object file
Crab.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Crab.cpp.o
.PHONY : Crab.cpp.o

Crab.i: Crab.cpp.i

.PHONY : Crab.i

# target to preprocess a source file
Crab.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Crab.cpp.i
.PHONY : Crab.cpp.i

Crab.s: Crab.cpp.s

.PHONY : Crab.s

# target to generate assembly for a file
Crab.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Crab.cpp.s
.PHONY : Crab.cpp.s

DeathScreen.o: DeathScreen.cpp.o

.PHONY : DeathScreen.o

# target to build an object file
DeathScreen.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/DeathScreen.cpp.o
.PHONY : DeathScreen.cpp.o

DeathScreen.i: DeathScreen.cpp.i

.PHONY : DeathScreen.i

# target to preprocess a source file
DeathScreen.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/DeathScreen.cpp.i
.PHONY : DeathScreen.cpp.i

DeathScreen.s: DeathScreen.cpp.s

.PHONY : DeathScreen.s

# target to generate assembly for a file
DeathScreen.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/DeathScreen.cpp.s
.PHONY : DeathScreen.cpp.s

Enemy.o: Enemy.cpp.o

.PHONY : Enemy.o

# target to build an object file
Enemy.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Enemy.cpp.o
.PHONY : Enemy.cpp.o

Enemy.i: Enemy.cpp.i

.PHONY : Enemy.i

# target to preprocess a source file
Enemy.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Enemy.cpp.i
.PHONY : Enemy.cpp.i

Enemy.s: Enemy.cpp.s

.PHONY : Enemy.s

# target to generate assembly for a file
Enemy.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Enemy.cpp.s
.PHONY : Enemy.cpp.s

EnergyPowerup.o: EnergyPowerup.cpp.o

.PHONY : EnergyPowerup.o

# target to build an object file
EnergyPowerup.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/EnergyPowerup.cpp.o
.PHONY : EnergyPowerup.cpp.o

EnergyPowerup.i: EnergyPowerup.cpp.i

.PHONY : EnergyPowerup.i

# target to preprocess a source file
EnergyPowerup.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/EnergyPowerup.cpp.i
.PHONY : EnergyPowerup.cpp.i

EnergyPowerup.s: EnergyPowerup.cpp.s

.PHONY : EnergyPowerup.s

# target to generate assembly for a file
EnergyPowerup.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/EnergyPowerup.cpp.s
.PHONY : EnergyPowerup.cpp.s

Entity.o: Entity.cpp.o

.PHONY : Entity.o

# target to build an object file
Entity.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Entity.cpp.o
.PHONY : Entity.cpp.o

Entity.i: Entity.cpp.i

.PHONY : Entity.i

# target to preprocess a source file
Entity.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Entity.cpp.i
.PHONY : Entity.cpp.i

Entity.s: Entity.cpp.s

.PHONY : Entity.s

# target to generate assembly for a file
Entity.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Entity.cpp.s
.PHONY : Entity.cpp.s

EntityHealthChangeText.o: EntityHealthChangeText.cpp.o

.PHONY : EntityHealthChangeText.o

# target to build an object file
EntityHealthChangeText.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/EntityHealthChangeText.cpp.o
.PHONY : EntityHealthChangeText.cpp.o

EntityHealthChangeText.i: EntityHealthChangeText.cpp.i

.PHONY : EntityHealthChangeText.i

# target to preprocess a source file
EntityHealthChangeText.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/EntityHealthChangeText.cpp.i
.PHONY : EntityHealthChangeText.cpp.i

EntityHealthChangeText.s: EntityHealthChangeText.cpp.s

.PHONY : EntityHealthChangeText.s

# target to generate assembly for a file
EntityHealthChangeText.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/EntityHealthChangeText.cpp.s
.PHONY : EntityHealthChangeText.cpp.s

EventHandler.o: EventHandler.cpp.o

.PHONY : EventHandler.o

# target to build an object file
EventHandler.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/EventHandler.cpp.o
.PHONY : EventHandler.cpp.o

EventHandler.i: EventHandler.cpp.i

.PHONY : EventHandler.i

# target to preprocess a source file
EventHandler.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/EventHandler.cpp.i
.PHONY : EventHandler.cpp.i

EventHandler.s: EventHandler.cpp.s

.PHONY : EventHandler.s

# target to generate assembly for a file
EventHandler.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/EventHandler.cpp.s
.PHONY : EventHandler.cpp.s

GUI.o: GUI.cpp.o

.PHONY : GUI.o

# target to build an object file
GUI.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/GUI.cpp.o
.PHONY : GUI.cpp.o

GUI.i: GUI.cpp.i

.PHONY : GUI.i

# target to preprocess a source file
GUI.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/GUI.cpp.i
.PHONY : GUI.cpp.i

GUI.s: GUI.cpp.s

.PHONY : GUI.s

# target to generate assembly for a file
GUI.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/GUI.cpp.s
.PHONY : GUI.cpp.s

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Game.cpp.s
.PHONY : Game.cpp.s

Graphics.o: Graphics.cpp.o

.PHONY : Graphics.o

# target to build an object file
Graphics.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Graphics.cpp.o
.PHONY : Graphics.cpp.o

Graphics.i: Graphics.cpp.i

.PHONY : Graphics.i

# target to preprocess a source file
Graphics.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Graphics.cpp.i
.PHONY : Graphics.cpp.i

Graphics.s: Graphics.cpp.s

.PHONY : Graphics.s

# target to generate assembly for a file
Graphics.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Graphics.cpp.s
.PHONY : Graphics.cpp.s

Item.o: Item.cpp.o

.PHONY : Item.o

# target to build an object file
Item.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Item.cpp.o
.PHONY : Item.cpp.o

Item.i: Item.cpp.i

.PHONY : Item.i

# target to preprocess a source file
Item.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Item.cpp.i
.PHONY : Item.cpp.i

Item.s: Item.cpp.s

.PHONY : Item.s

# target to generate assembly for a file
Item.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Item.cpp.s
.PHONY : Item.cpp.s

Laser.o: Laser.cpp.o

.PHONY : Laser.o

# target to build an object file
Laser.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Laser.cpp.o
.PHONY : Laser.cpp.o

Laser.i: Laser.cpp.i

.PHONY : Laser.i

# target to preprocess a source file
Laser.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Laser.cpp.i
.PHONY : Laser.cpp.i

Laser.s: Laser.cpp.s

.PHONY : Laser.s

# target to generate assembly for a file
Laser.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Laser.cpp.s
.PHONY : Laser.cpp.s

Multiplayer.o: Multiplayer.cpp.o

.PHONY : Multiplayer.o

# target to build an object file
Multiplayer.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Multiplayer.cpp.o
.PHONY : Multiplayer.cpp.o

Multiplayer.i: Multiplayer.cpp.i

.PHONY : Multiplayer.i

# target to preprocess a source file
Multiplayer.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Multiplayer.cpp.i
.PHONY : Multiplayer.cpp.i

Multiplayer.s: Multiplayer.cpp.s

.PHONY : Multiplayer.s

# target to generate assembly for a file
Multiplayer.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Multiplayer.cpp.s
.PHONY : Multiplayer.cpp.s

Orb.o: Orb.cpp.o

.PHONY : Orb.o

# target to build an object file
Orb.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Orb.cpp.o
.PHONY : Orb.cpp.o

Orb.i: Orb.cpp.i

.PHONY : Orb.i

# target to preprocess a source file
Orb.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Orb.cpp.i
.PHONY : Orb.cpp.i

Orb.s: Orb.cpp.s

.PHONY : Orb.s

# target to generate assembly for a file
Orb.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Orb.cpp.s
.PHONY : Orb.cpp.s

Particle.o: Particle.cpp.o

.PHONY : Particle.o

# target to build an object file
Particle.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Particle.cpp.o
.PHONY : Particle.cpp.o

Particle.i: Particle.cpp.i

.PHONY : Particle.i

# target to preprocess a source file
Particle.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Particle.cpp.i
.PHONY : Particle.cpp.i

Particle.s: Particle.cpp.s

.PHONY : Particle.s

# target to generate assembly for a file
Particle.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Particle.cpp.s
.PHONY : Particle.cpp.s

PauseScreen.o: PauseScreen.cpp.o

.PHONY : PauseScreen.o

# target to build an object file
PauseScreen.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/PauseScreen.cpp.o
.PHONY : PauseScreen.cpp.o

PauseScreen.i: PauseScreen.cpp.i

.PHONY : PauseScreen.i

# target to preprocess a source file
PauseScreen.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/PauseScreen.cpp.i
.PHONY : PauseScreen.cpp.i

PauseScreen.s: PauseScreen.cpp.s

.PHONY : PauseScreen.s

# target to generate assembly for a file
PauseScreen.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/PauseScreen.cpp.s
.PHONY : PauseScreen.cpp.s

Player.o: Player.cpp.o

.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i

.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s

.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Player.cpp.s
.PHONY : Player.cpp.s

Powerup.o: Powerup.cpp.o

.PHONY : Powerup.o

# target to build an object file
Powerup.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Powerup.cpp.o
.PHONY : Powerup.cpp.o

Powerup.i: Powerup.cpp.i

.PHONY : Powerup.i

# target to preprocess a source file
Powerup.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Powerup.cpp.i
.PHONY : Powerup.cpp.i

Powerup.s: Powerup.cpp.s

.PHONY : Powerup.s

# target to generate assembly for a file
Powerup.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Powerup.cpp.s
.PHONY : Powerup.cpp.s

RegenerationPowerup.o: RegenerationPowerup.cpp.o

.PHONY : RegenerationPowerup.o

# target to build an object file
RegenerationPowerup.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/RegenerationPowerup.cpp.o
.PHONY : RegenerationPowerup.cpp.o

RegenerationPowerup.i: RegenerationPowerup.cpp.i

.PHONY : RegenerationPowerup.i

# target to preprocess a source file
RegenerationPowerup.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/RegenerationPowerup.cpp.i
.PHONY : RegenerationPowerup.cpp.i

RegenerationPowerup.s: RegenerationPowerup.cpp.s

.PHONY : RegenerationPowerup.s

# target to generate assembly for a file
RegenerationPowerup.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/RegenerationPowerup.cpp.s
.PHONY : RegenerationPowerup.cpp.s

Shop.o: Shop.cpp.o

.PHONY : Shop.o

# target to build an object file
Shop.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Shop.cpp.o
.PHONY : Shop.cpp.o

Shop.i: Shop.cpp.i

.PHONY : Shop.i

# target to preprocess a source file
Shop.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Shop.cpp.i
.PHONY : Shop.cpp.i

Shop.s: Shop.cpp.s

.PHONY : Shop.s

# target to generate assembly for a file
Shop.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Shop.cpp.s
.PHONY : Shop.cpp.s

Space.o: Space.cpp.o

.PHONY : Space.o

# target to build an object file
Space.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Space.cpp.o
.PHONY : Space.cpp.o

Space.i: Space.cpp.i

.PHONY : Space.i

# target to preprocess a source file
Space.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Space.cpp.i
.PHONY : Space.cpp.i

Space.s: Space.cpp.s

.PHONY : Space.s

# target to generate assembly for a file
Space.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Space.cpp.s
.PHONY : Space.cpp.s

TextObject.o: TextObject.cpp.o

.PHONY : TextObject.o

# target to build an object file
TextObject.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/TextObject.cpp.o
.PHONY : TextObject.cpp.o

TextObject.i: TextObject.cpp.i

.PHONY : TextObject.i

# target to preprocess a source file
TextObject.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/TextObject.cpp.i
.PHONY : TextObject.cpp.i

TextObject.s: TextObject.cpp.s

.PHONY : TextObject.s

# target to generate assembly for a file
TextObject.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/TextObject.cpp.s
.PHONY : TextObject.cpp.s

Texture.o: Texture.cpp.o

.PHONY : Texture.o

# target to build an object file
Texture.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Texture.cpp.o
.PHONY : Texture.cpp.o

Texture.i: Texture.cpp.i

.PHONY : Texture.i

# target to preprocess a source file
Texture.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Texture.cpp.i
.PHONY : Texture.cpp.i

Texture.s: Texture.cpp.s

.PHONY : Texture.s

# target to generate assembly for a file
Texture.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Texture.cpp.s
.PHONY : Texture.cpp.s

TitleScreen.o: TitleScreen.cpp.o

.PHONY : TitleScreen.o

# target to build an object file
TitleScreen.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/TitleScreen.cpp.o
.PHONY : TitleScreen.cpp.o

TitleScreen.i: TitleScreen.cpp.i

.PHONY : TitleScreen.i

# target to preprocess a source file
TitleScreen.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/TitleScreen.cpp.i
.PHONY : TitleScreen.cpp.i

TitleScreen.s: TitleScreen.cpp.s

.PHONY : TitleScreen.s

# target to generate assembly for a file
TitleScreen.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/TitleScreen.cpp.s
.PHONY : TitleScreen.cpp.s

Turret.o: Turret.cpp.o

.PHONY : Turret.o

# target to build an object file
Turret.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Turret.cpp.o
.PHONY : Turret.cpp.o

Turret.i: Turret.cpp.i

.PHONY : Turret.i

# target to preprocess a source file
Turret.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Turret.cpp.i
.PHONY : Turret.cpp.i

Turret.s: Turret.cpp.s

.PHONY : Turret.s

# target to generate assembly for a file
Turret.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Turret.cpp.s
.PHONY : Turret.cpp.s

Upgrades.o: Upgrades.cpp.o

.PHONY : Upgrades.o

# target to build an object file
Upgrades.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Upgrades.cpp.o
.PHONY : Upgrades.cpp.o

Upgrades.i: Upgrades.cpp.i

.PHONY : Upgrades.i

# target to preprocess a source file
Upgrades.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Upgrades.cpp.i
.PHONY : Upgrades.cpp.i

Upgrades.s: Upgrades.cpp.s

.PHONY : Upgrades.s

# target to generate assembly for a file
Upgrades.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Upgrades.cpp.s
.PHONY : Upgrades.cpp.s

Utilities.o: Utilities.cpp.o

.PHONY : Utilities.o

# target to build an object file
Utilities.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Utilities.cpp.o
.PHONY : Utilities.cpp.o

Utilities.i: Utilities.cpp.i

.PHONY : Utilities.i

# target to preprocess a source file
Utilities.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Utilities.cpp.i
.PHONY : Utilities.cpp.i

Utilities.s: Utilities.cpp.s

.PHONY : Utilities.s

# target to generate assembly for a file
Utilities.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/Utilities.cpp.s
.PHONY : Utilities.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(MAKE) -f Margarita/CMakeFiles/Margarita.dir/build.make Margarita/CMakeFiles/Margarita.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Margarita"
	@echo "... AirStrike.o"
	@echo "... AirStrike.i"
	@echo "... AirStrike.s"
	@echo "... Animation.o"
	@echo "... Animation.i"
	@echo "... Animation.s"
	@echo "... Block.o"
	@echo "... Block.i"
	@echo "... Block.s"
	@echo "... Bomb.o"
	@echo "... Bomb.i"
	@echo "... Bomb.s"
	@echo "... BombAnimation.o"
	@echo "... BombAnimation.i"
	@echo "... BombAnimation.s"
	@echo "... Coin.o"
	@echo "... Coin.i"
	@echo "... Coin.s"
	@echo "... Comet.o"
	@echo "... Comet.i"
	@echo "... Comet.s"
	@echo "... ControlManager.o"
	@echo "... ControlManager.i"
	@echo "... ControlManager.s"
	@echo "... ControlsScreen.o"
	@echo "... ControlsScreen.i"
	@echo "... ControlsScreen.s"
	@echo "... Crab.o"
	@echo "... Crab.i"
	@echo "... Crab.s"
	@echo "... DeathScreen.o"
	@echo "... DeathScreen.i"
	@echo "... DeathScreen.s"
	@echo "... Enemy.o"
	@echo "... Enemy.i"
	@echo "... Enemy.s"
	@echo "... EnergyPowerup.o"
	@echo "... EnergyPowerup.i"
	@echo "... EnergyPowerup.s"
	@echo "... Entity.o"
	@echo "... Entity.i"
	@echo "... Entity.s"
	@echo "... EntityHealthChangeText.o"
	@echo "... EntityHealthChangeText.i"
	@echo "... EntityHealthChangeText.s"
	@echo "... EventHandler.o"
	@echo "... EventHandler.i"
	@echo "... EventHandler.s"
	@echo "... GUI.o"
	@echo "... GUI.i"
	@echo "... GUI.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... Graphics.o"
	@echo "... Graphics.i"
	@echo "... Graphics.s"
	@echo "... Item.o"
	@echo "... Item.i"
	@echo "... Item.s"
	@echo "... Laser.o"
	@echo "... Laser.i"
	@echo "... Laser.s"
	@echo "... Multiplayer.o"
	@echo "... Multiplayer.i"
	@echo "... Multiplayer.s"
	@echo "... Orb.o"
	@echo "... Orb.i"
	@echo "... Orb.s"
	@echo "... Particle.o"
	@echo "... Particle.i"
	@echo "... Particle.s"
	@echo "... PauseScreen.o"
	@echo "... PauseScreen.i"
	@echo "... PauseScreen.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... Powerup.o"
	@echo "... Powerup.i"
	@echo "... Powerup.s"
	@echo "... RegenerationPowerup.o"
	@echo "... RegenerationPowerup.i"
	@echo "... RegenerationPowerup.s"
	@echo "... Shop.o"
	@echo "... Shop.i"
	@echo "... Shop.s"
	@echo "... Space.o"
	@echo "... Space.i"
	@echo "... Space.s"
	@echo "... TextObject.o"
	@echo "... TextObject.i"
	@echo "... TextObject.s"
	@echo "... Texture.o"
	@echo "... Texture.i"
	@echo "... Texture.s"
	@echo "... TitleScreen.o"
	@echo "... TitleScreen.i"
	@echo "... TitleScreen.s"
	@echo "... Turret.o"
	@echo "... Turret.i"
	@echo "... Turret.s"
	@echo "... Upgrades.o"
	@echo "... Upgrades.i"
	@echo "... Upgrades.s"
	@echo "... Utilities.o"
	@echo "... Utilities.i"
	@echo "... Utilities.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /mnt/c/Users/Joel/Desktop/Margarita && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

