# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Joel/Desktop/Margarita/Margarita

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Joel/Desktop/Margarita/Margarita

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Joel/Desktop/Margarita/Margarita/CMakeFiles /mnt/c/Users/Joel/Desktop/Margarita/Margarita/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Joel/Desktop/Margarita/Margarita/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /mnt/c/Users/Joel/Desktop/Margarita/Margarita/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Margarita

# Build rule for target.
Margarita: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Margarita
.PHONY : Margarita

# fast build rule for target.
Margarita/fast:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/build
.PHONY : Margarita/fast

src/AirStrike.o: src/AirStrike.cpp.o

.PHONY : src/AirStrike.o

# target to build an object file
src/AirStrike.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/AirStrike.cpp.o
.PHONY : src/AirStrike.cpp.o

src/AirStrike.i: src/AirStrike.cpp.i

.PHONY : src/AirStrike.i

# target to preprocess a source file
src/AirStrike.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/AirStrike.cpp.i
.PHONY : src/AirStrike.cpp.i

src/AirStrike.s: src/AirStrike.cpp.s

.PHONY : src/AirStrike.s

# target to generate assembly for a file
src/AirStrike.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/AirStrike.cpp.s
.PHONY : src/AirStrike.cpp.s

src/Animation.o: src/Animation.cpp.o

.PHONY : src/Animation.o

# target to build an object file
src/Animation.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Animation.cpp.o
.PHONY : src/Animation.cpp.o

src/Animation.i: src/Animation.cpp.i

.PHONY : src/Animation.i

# target to preprocess a source file
src/Animation.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Animation.cpp.i
.PHONY : src/Animation.cpp.i

src/Animation.s: src/Animation.cpp.s

.PHONY : src/Animation.s

# target to generate assembly for a file
src/Animation.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Animation.cpp.s
.PHONY : src/Animation.cpp.s

src/Block.o: src/Block.cpp.o

.PHONY : src/Block.o

# target to build an object file
src/Block.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Block.cpp.o
.PHONY : src/Block.cpp.o

src/Block.i: src/Block.cpp.i

.PHONY : src/Block.i

# target to preprocess a source file
src/Block.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Block.cpp.i
.PHONY : src/Block.cpp.i

src/Block.s: src/Block.cpp.s

.PHONY : src/Block.s

# target to generate assembly for a file
src/Block.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Block.cpp.s
.PHONY : src/Block.cpp.s

src/Bomb.o: src/Bomb.cpp.o

.PHONY : src/Bomb.o

# target to build an object file
src/Bomb.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Bomb.cpp.o
.PHONY : src/Bomb.cpp.o

src/Bomb.i: src/Bomb.cpp.i

.PHONY : src/Bomb.i

# target to preprocess a source file
src/Bomb.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Bomb.cpp.i
.PHONY : src/Bomb.cpp.i

src/Bomb.s: src/Bomb.cpp.s

.PHONY : src/Bomb.s

# target to generate assembly for a file
src/Bomb.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Bomb.cpp.s
.PHONY : src/Bomb.cpp.s

src/BombAnimation.o: src/BombAnimation.cpp.o

.PHONY : src/BombAnimation.o

# target to build an object file
src/BombAnimation.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/BombAnimation.cpp.o
.PHONY : src/BombAnimation.cpp.o

src/BombAnimation.i: src/BombAnimation.cpp.i

.PHONY : src/BombAnimation.i

# target to preprocess a source file
src/BombAnimation.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/BombAnimation.cpp.i
.PHONY : src/BombAnimation.cpp.i

src/BombAnimation.s: src/BombAnimation.cpp.s

.PHONY : src/BombAnimation.s

# target to generate assembly for a file
src/BombAnimation.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/BombAnimation.cpp.s
.PHONY : src/BombAnimation.cpp.s

src/Coin.o: src/Coin.cpp.o

.PHONY : src/Coin.o

# target to build an object file
src/Coin.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Coin.cpp.o
.PHONY : src/Coin.cpp.o

src/Coin.i: src/Coin.cpp.i

.PHONY : src/Coin.i

# target to preprocess a source file
src/Coin.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Coin.cpp.i
.PHONY : src/Coin.cpp.i

src/Coin.s: src/Coin.cpp.s

.PHONY : src/Coin.s

# target to generate assembly for a file
src/Coin.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Coin.cpp.s
.PHONY : src/Coin.cpp.s

src/Comet.o: src/Comet.cpp.o

.PHONY : src/Comet.o

# target to build an object file
src/Comet.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Comet.cpp.o
.PHONY : src/Comet.cpp.o

src/Comet.i: src/Comet.cpp.i

.PHONY : src/Comet.i

# target to preprocess a source file
src/Comet.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Comet.cpp.i
.PHONY : src/Comet.cpp.i

src/Comet.s: src/Comet.cpp.s

.PHONY : src/Comet.s

# target to generate assembly for a file
src/Comet.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Comet.cpp.s
.PHONY : src/Comet.cpp.s

src/ControlManager.o: src/ControlManager.cpp.o

.PHONY : src/ControlManager.o

# target to build an object file
src/ControlManager.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/ControlManager.cpp.o
.PHONY : src/ControlManager.cpp.o

src/ControlManager.i: src/ControlManager.cpp.i

.PHONY : src/ControlManager.i

# target to preprocess a source file
src/ControlManager.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/ControlManager.cpp.i
.PHONY : src/ControlManager.cpp.i

src/ControlManager.s: src/ControlManager.cpp.s

.PHONY : src/ControlManager.s

# target to generate assembly for a file
src/ControlManager.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/ControlManager.cpp.s
.PHONY : src/ControlManager.cpp.s

src/ControlsScreen.o: src/ControlsScreen.cpp.o

.PHONY : src/ControlsScreen.o

# target to build an object file
src/ControlsScreen.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/ControlsScreen.cpp.o
.PHONY : src/ControlsScreen.cpp.o

src/ControlsScreen.i: src/ControlsScreen.cpp.i

.PHONY : src/ControlsScreen.i

# target to preprocess a source file
src/ControlsScreen.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/ControlsScreen.cpp.i
.PHONY : src/ControlsScreen.cpp.i

src/ControlsScreen.s: src/ControlsScreen.cpp.s

.PHONY : src/ControlsScreen.s

# target to generate assembly for a file
src/ControlsScreen.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/ControlsScreen.cpp.s
.PHONY : src/ControlsScreen.cpp.s

src/Crab.o: src/Crab.cpp.o

.PHONY : src/Crab.o

# target to build an object file
src/Crab.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Crab.cpp.o
.PHONY : src/Crab.cpp.o

src/Crab.i: src/Crab.cpp.i

.PHONY : src/Crab.i

# target to preprocess a source file
src/Crab.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Crab.cpp.i
.PHONY : src/Crab.cpp.i

src/Crab.s: src/Crab.cpp.s

.PHONY : src/Crab.s

# target to generate assembly for a file
src/Crab.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Crab.cpp.s
.PHONY : src/Crab.cpp.s

src/DeathScreen.o: src/DeathScreen.cpp.o

.PHONY : src/DeathScreen.o

# target to build an object file
src/DeathScreen.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/DeathScreen.cpp.o
.PHONY : src/DeathScreen.cpp.o

src/DeathScreen.i: src/DeathScreen.cpp.i

.PHONY : src/DeathScreen.i

# target to preprocess a source file
src/DeathScreen.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/DeathScreen.cpp.i
.PHONY : src/DeathScreen.cpp.i

src/DeathScreen.s: src/DeathScreen.cpp.s

.PHONY : src/DeathScreen.s

# target to generate assembly for a file
src/DeathScreen.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/DeathScreen.cpp.s
.PHONY : src/DeathScreen.cpp.s

src/Enemy.o: src/Enemy.cpp.o

.PHONY : src/Enemy.o

# target to build an object file
src/Enemy.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Enemy.cpp.o
.PHONY : src/Enemy.cpp.o

src/Enemy.i: src/Enemy.cpp.i

.PHONY : src/Enemy.i

# target to preprocess a source file
src/Enemy.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Enemy.cpp.i
.PHONY : src/Enemy.cpp.i

src/Enemy.s: src/Enemy.cpp.s

.PHONY : src/Enemy.s

# target to generate assembly for a file
src/Enemy.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Enemy.cpp.s
.PHONY : src/Enemy.cpp.s

src/EnergyPowerup.o: src/EnergyPowerup.cpp.o

.PHONY : src/EnergyPowerup.o

# target to build an object file
src/EnergyPowerup.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/EnergyPowerup.cpp.o
.PHONY : src/EnergyPowerup.cpp.o

src/EnergyPowerup.i: src/EnergyPowerup.cpp.i

.PHONY : src/EnergyPowerup.i

# target to preprocess a source file
src/EnergyPowerup.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/EnergyPowerup.cpp.i
.PHONY : src/EnergyPowerup.cpp.i

src/EnergyPowerup.s: src/EnergyPowerup.cpp.s

.PHONY : src/EnergyPowerup.s

# target to generate assembly for a file
src/EnergyPowerup.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/EnergyPowerup.cpp.s
.PHONY : src/EnergyPowerup.cpp.s

src/Entity.o: src/Entity.cpp.o

.PHONY : src/Entity.o

# target to build an object file
src/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Entity.cpp.o
.PHONY : src/Entity.cpp.o

src/Entity.i: src/Entity.cpp.i

.PHONY : src/Entity.i

# target to preprocess a source file
src/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Entity.cpp.i
.PHONY : src/Entity.cpp.i

src/Entity.s: src/Entity.cpp.s

.PHONY : src/Entity.s

# target to generate assembly for a file
src/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Entity.cpp.s
.PHONY : src/Entity.cpp.s

src/EntityHealthChangeText.o: src/EntityHealthChangeText.cpp.o

.PHONY : src/EntityHealthChangeText.o

# target to build an object file
src/EntityHealthChangeText.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/EntityHealthChangeText.cpp.o
.PHONY : src/EntityHealthChangeText.cpp.o

src/EntityHealthChangeText.i: src/EntityHealthChangeText.cpp.i

.PHONY : src/EntityHealthChangeText.i

# target to preprocess a source file
src/EntityHealthChangeText.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/EntityHealthChangeText.cpp.i
.PHONY : src/EntityHealthChangeText.cpp.i

src/EntityHealthChangeText.s: src/EntityHealthChangeText.cpp.s

.PHONY : src/EntityHealthChangeText.s

# target to generate assembly for a file
src/EntityHealthChangeText.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/EntityHealthChangeText.cpp.s
.PHONY : src/EntityHealthChangeText.cpp.s

src/EventHandler.o: src/EventHandler.cpp.o

.PHONY : src/EventHandler.o

# target to build an object file
src/EventHandler.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/EventHandler.cpp.o
.PHONY : src/EventHandler.cpp.o

src/EventHandler.i: src/EventHandler.cpp.i

.PHONY : src/EventHandler.i

# target to preprocess a source file
src/EventHandler.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/EventHandler.cpp.i
.PHONY : src/EventHandler.cpp.i

src/EventHandler.s: src/EventHandler.cpp.s

.PHONY : src/EventHandler.s

# target to generate assembly for a file
src/EventHandler.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/EventHandler.cpp.s
.PHONY : src/EventHandler.cpp.s

src/GUI.o: src/GUI.cpp.o

.PHONY : src/GUI.o

# target to build an object file
src/GUI.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/GUI.cpp.o
.PHONY : src/GUI.cpp.o

src/GUI.i: src/GUI.cpp.i

.PHONY : src/GUI.i

# target to preprocess a source file
src/GUI.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/GUI.cpp.i
.PHONY : src/GUI.cpp.i

src/GUI.s: src/GUI.cpp.s

.PHONY : src/GUI.s

# target to generate assembly for a file
src/GUI.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/GUI.cpp.s
.PHONY : src/GUI.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Graphics.o: src/Graphics.cpp.o

.PHONY : src/Graphics.o

# target to build an object file
src/Graphics.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Graphics.cpp.o
.PHONY : src/Graphics.cpp.o

src/Graphics.i: src/Graphics.cpp.i

.PHONY : src/Graphics.i

# target to preprocess a source file
src/Graphics.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Graphics.cpp.i
.PHONY : src/Graphics.cpp.i

src/Graphics.s: src/Graphics.cpp.s

.PHONY : src/Graphics.s

# target to generate assembly for a file
src/Graphics.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Graphics.cpp.s
.PHONY : src/Graphics.cpp.s

src/Items/Item.o: src/Items/Item.cpp.o

.PHONY : src/Items/Item.o

# target to build an object file
src/Items/Item.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Items/Item.cpp.o
.PHONY : src/Items/Item.cpp.o

src/Items/Item.i: src/Items/Item.cpp.i

.PHONY : src/Items/Item.i

# target to preprocess a source file
src/Items/Item.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Items/Item.cpp.i
.PHONY : src/Items/Item.cpp.i

src/Items/Item.s: src/Items/Item.cpp.s

.PHONY : src/Items/Item.s

# target to generate assembly for a file
src/Items/Item.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Items/Item.cpp.s
.PHONY : src/Items/Item.cpp.s

src/Laser.o: src/Laser.cpp.o

.PHONY : src/Laser.o

# target to build an object file
src/Laser.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Laser.cpp.o
.PHONY : src/Laser.cpp.o

src/Laser.i: src/Laser.cpp.i

.PHONY : src/Laser.i

# target to preprocess a source file
src/Laser.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Laser.cpp.i
.PHONY : src/Laser.cpp.i

src/Laser.s: src/Laser.cpp.s

.PHONY : src/Laser.s

# target to generate assembly for a file
src/Laser.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Laser.cpp.s
.PHONY : src/Laser.cpp.s

src/Multiplayer.o: src/Multiplayer.cpp.o

.PHONY : src/Multiplayer.o

# target to build an object file
src/Multiplayer.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Multiplayer.cpp.o
.PHONY : src/Multiplayer.cpp.o

src/Multiplayer.i: src/Multiplayer.cpp.i

.PHONY : src/Multiplayer.i

# target to preprocess a source file
src/Multiplayer.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Multiplayer.cpp.i
.PHONY : src/Multiplayer.cpp.i

src/Multiplayer.s: src/Multiplayer.cpp.s

.PHONY : src/Multiplayer.s

# target to generate assembly for a file
src/Multiplayer.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Multiplayer.cpp.s
.PHONY : src/Multiplayer.cpp.s

src/Orb.o: src/Orb.cpp.o

.PHONY : src/Orb.o

# target to build an object file
src/Orb.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Orb.cpp.o
.PHONY : src/Orb.cpp.o

src/Orb.i: src/Orb.cpp.i

.PHONY : src/Orb.i

# target to preprocess a source file
src/Orb.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Orb.cpp.i
.PHONY : src/Orb.cpp.i

src/Orb.s: src/Orb.cpp.s

.PHONY : src/Orb.s

# target to generate assembly for a file
src/Orb.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Orb.cpp.s
.PHONY : src/Orb.cpp.s

src/Particle.o: src/Particle.cpp.o

.PHONY : src/Particle.o

# target to build an object file
src/Particle.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Particle.cpp.o
.PHONY : src/Particle.cpp.o

src/Particle.i: src/Particle.cpp.i

.PHONY : src/Particle.i

# target to preprocess a source file
src/Particle.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Particle.cpp.i
.PHONY : src/Particle.cpp.i

src/Particle.s: src/Particle.cpp.s

.PHONY : src/Particle.s

# target to generate assembly for a file
src/Particle.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Particle.cpp.s
.PHONY : src/Particle.cpp.s

src/PauseScreen.o: src/PauseScreen.cpp.o

.PHONY : src/PauseScreen.o

# target to build an object file
src/PauseScreen.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/PauseScreen.cpp.o
.PHONY : src/PauseScreen.cpp.o

src/PauseScreen.i: src/PauseScreen.cpp.i

.PHONY : src/PauseScreen.i

# target to preprocess a source file
src/PauseScreen.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/PauseScreen.cpp.i
.PHONY : src/PauseScreen.cpp.i

src/PauseScreen.s: src/PauseScreen.cpp.s

.PHONY : src/PauseScreen.s

# target to generate assembly for a file
src/PauseScreen.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/PauseScreen.cpp.s
.PHONY : src/PauseScreen.cpp.s

src/Player.o: src/Player.cpp.o

.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i

.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s

.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/Powerup.o: src/Powerup.cpp.o

.PHONY : src/Powerup.o

# target to build an object file
src/Powerup.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Powerup.cpp.o
.PHONY : src/Powerup.cpp.o

src/Powerup.i: src/Powerup.cpp.i

.PHONY : src/Powerup.i

# target to preprocess a source file
src/Powerup.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Powerup.cpp.i
.PHONY : src/Powerup.cpp.i

src/Powerup.s: src/Powerup.cpp.s

.PHONY : src/Powerup.s

# target to generate assembly for a file
src/Powerup.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Powerup.cpp.s
.PHONY : src/Powerup.cpp.s

src/RegenerationPowerup.o: src/RegenerationPowerup.cpp.o

.PHONY : src/RegenerationPowerup.o

# target to build an object file
src/RegenerationPowerup.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/RegenerationPowerup.cpp.o
.PHONY : src/RegenerationPowerup.cpp.o

src/RegenerationPowerup.i: src/RegenerationPowerup.cpp.i

.PHONY : src/RegenerationPowerup.i

# target to preprocess a source file
src/RegenerationPowerup.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/RegenerationPowerup.cpp.i
.PHONY : src/RegenerationPowerup.cpp.i

src/RegenerationPowerup.s: src/RegenerationPowerup.cpp.s

.PHONY : src/RegenerationPowerup.s

# target to generate assembly for a file
src/RegenerationPowerup.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/RegenerationPowerup.cpp.s
.PHONY : src/RegenerationPowerup.cpp.s

src/Shop.o: src/Shop.cpp.o

.PHONY : src/Shop.o

# target to build an object file
src/Shop.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Shop.cpp.o
.PHONY : src/Shop.cpp.o

src/Shop.i: src/Shop.cpp.i

.PHONY : src/Shop.i

# target to preprocess a source file
src/Shop.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Shop.cpp.i
.PHONY : src/Shop.cpp.i

src/Shop.s: src/Shop.cpp.s

.PHONY : src/Shop.s

# target to generate assembly for a file
src/Shop.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Shop.cpp.s
.PHONY : src/Shop.cpp.s

src/Snail.o: src/Snail.cpp.o

.PHONY : src/Snail.o

# target to build an object file
src/Snail.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Snail.cpp.o
.PHONY : src/Snail.cpp.o

src/Snail.i: src/Snail.cpp.i

.PHONY : src/Snail.i

# target to preprocess a source file
src/Snail.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Snail.cpp.i
.PHONY : src/Snail.cpp.i

src/Snail.s: src/Snail.cpp.s

.PHONY : src/Snail.s

# target to generate assembly for a file
src/Snail.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Snail.cpp.s
.PHONY : src/Snail.cpp.s

src/Space.o: src/Space.cpp.o

.PHONY : src/Space.o

# target to build an object file
src/Space.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Space.cpp.o
.PHONY : src/Space.cpp.o

src/Space.i: src/Space.cpp.i

.PHONY : src/Space.i

# target to preprocess a source file
src/Space.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Space.cpp.i
.PHONY : src/Space.cpp.i

src/Space.s: src/Space.cpp.s

.PHONY : src/Space.s

# target to generate assembly for a file
src/Space.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Space.cpp.s
.PHONY : src/Space.cpp.s

src/TextObject.o: src/TextObject.cpp.o

.PHONY : src/TextObject.o

# target to build an object file
src/TextObject.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/TextObject.cpp.o
.PHONY : src/TextObject.cpp.o

src/TextObject.i: src/TextObject.cpp.i

.PHONY : src/TextObject.i

# target to preprocess a source file
src/TextObject.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/TextObject.cpp.i
.PHONY : src/TextObject.cpp.i

src/TextObject.s: src/TextObject.cpp.s

.PHONY : src/TextObject.s

# target to generate assembly for a file
src/TextObject.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/TextObject.cpp.s
.PHONY : src/TextObject.cpp.s

src/Texture.o: src/Texture.cpp.o

.PHONY : src/Texture.o

# target to build an object file
src/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Texture.cpp.o
.PHONY : src/Texture.cpp.o

src/Texture.i: src/Texture.cpp.i

.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s

.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/TitleScreen.o: src/TitleScreen.cpp.o

.PHONY : src/TitleScreen.o

# target to build an object file
src/TitleScreen.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/TitleScreen.cpp.o
.PHONY : src/TitleScreen.cpp.o

src/TitleScreen.i: src/TitleScreen.cpp.i

.PHONY : src/TitleScreen.i

# target to preprocess a source file
src/TitleScreen.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/TitleScreen.cpp.i
.PHONY : src/TitleScreen.cpp.i

src/TitleScreen.s: src/TitleScreen.cpp.s

.PHONY : src/TitleScreen.s

# target to generate assembly for a file
src/TitleScreen.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/TitleScreen.cpp.s
.PHONY : src/TitleScreen.cpp.s

src/Turret.o: src/Turret.cpp.o

.PHONY : src/Turret.o

# target to build an object file
src/Turret.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Turret.cpp.o
.PHONY : src/Turret.cpp.o

src/Turret.i: src/Turret.cpp.i

.PHONY : src/Turret.i

# target to preprocess a source file
src/Turret.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Turret.cpp.i
.PHONY : src/Turret.cpp.i

src/Turret.s: src/Turret.cpp.s

.PHONY : src/Turret.s

# target to generate assembly for a file
src/Turret.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Turret.cpp.s
.PHONY : src/Turret.cpp.s

src/Upgrades.o: src/Upgrades.cpp.o

.PHONY : src/Upgrades.o

# target to build an object file
src/Upgrades.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Upgrades.cpp.o
.PHONY : src/Upgrades.cpp.o

src/Upgrades.i: src/Upgrades.cpp.i

.PHONY : src/Upgrades.i

# target to preprocess a source file
src/Upgrades.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Upgrades.cpp.i
.PHONY : src/Upgrades.cpp.i

src/Upgrades.s: src/Upgrades.cpp.s

.PHONY : src/Upgrades.s

# target to generate assembly for a file
src/Upgrades.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Upgrades.cpp.s
.PHONY : src/Upgrades.cpp.s

src/Utilities.o: src/Utilities.cpp.o

.PHONY : src/Utilities.o

# target to build an object file
src/Utilities.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Utilities.cpp.o
.PHONY : src/Utilities.cpp.o

src/Utilities.i: src/Utilities.cpp.i

.PHONY : src/Utilities.i

# target to preprocess a source file
src/Utilities.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Utilities.cpp.i
.PHONY : src/Utilities.cpp.i

src/Utilities.s: src/Utilities.cpp.s

.PHONY : src/Utilities.s

# target to generate assembly for a file
src/Utilities.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/Utilities.cpp.s
.PHONY : src/Utilities.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Margarita.dir/build.make CMakeFiles/Margarita.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Margarita"
	@echo "... src/AirStrike.o"
	@echo "... src/AirStrike.i"
	@echo "... src/AirStrike.s"
	@echo "... src/Animation.o"
	@echo "... src/Animation.i"
	@echo "... src/Animation.s"
	@echo "... src/Block.o"
	@echo "... src/Block.i"
	@echo "... src/Block.s"
	@echo "... src/Bomb.o"
	@echo "... src/Bomb.i"
	@echo "... src/Bomb.s"
	@echo "... src/BombAnimation.o"
	@echo "... src/BombAnimation.i"
	@echo "... src/BombAnimation.s"
	@echo "... src/Coin.o"
	@echo "... src/Coin.i"
	@echo "... src/Coin.s"
	@echo "... src/Comet.o"
	@echo "... src/Comet.i"
	@echo "... src/Comet.s"
	@echo "... src/ControlManager.o"
	@echo "... src/ControlManager.i"
	@echo "... src/ControlManager.s"
	@echo "... src/ControlsScreen.o"
	@echo "... src/ControlsScreen.i"
	@echo "... src/ControlsScreen.s"
	@echo "... src/Crab.o"
	@echo "... src/Crab.i"
	@echo "... src/Crab.s"
	@echo "... src/DeathScreen.o"
	@echo "... src/DeathScreen.i"
	@echo "... src/DeathScreen.s"
	@echo "... src/Enemy.o"
	@echo "... src/Enemy.i"
	@echo "... src/Enemy.s"
	@echo "... src/EnergyPowerup.o"
	@echo "... src/EnergyPowerup.i"
	@echo "... src/EnergyPowerup.s"
	@echo "... src/Entity.o"
	@echo "... src/Entity.i"
	@echo "... src/Entity.s"
	@echo "... src/EntityHealthChangeText.o"
	@echo "... src/EntityHealthChangeText.i"
	@echo "... src/EntityHealthChangeText.s"
	@echo "... src/EventHandler.o"
	@echo "... src/EventHandler.i"
	@echo "... src/EventHandler.s"
	@echo "... src/GUI.o"
	@echo "... src/GUI.i"
	@echo "... src/GUI.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/Graphics.o"
	@echo "... src/Graphics.i"
	@echo "... src/Graphics.s"
	@echo "... src/Items/Item.o"
	@echo "... src/Items/Item.i"
	@echo "... src/Items/Item.s"
	@echo "... src/Laser.o"
	@echo "... src/Laser.i"
	@echo "... src/Laser.s"
	@echo "... src/Multiplayer.o"
	@echo "... src/Multiplayer.i"
	@echo "... src/Multiplayer.s"
	@echo "... src/Orb.o"
	@echo "... src/Orb.i"
	@echo "... src/Orb.s"
	@echo "... src/Particle.o"
	@echo "... src/Particle.i"
	@echo "... src/Particle.s"
	@echo "... src/PauseScreen.o"
	@echo "... src/PauseScreen.i"
	@echo "... src/PauseScreen.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/Powerup.o"
	@echo "... src/Powerup.i"
	@echo "... src/Powerup.s"
	@echo "... src/RegenerationPowerup.o"
	@echo "... src/RegenerationPowerup.i"
	@echo "... src/RegenerationPowerup.s"
	@echo "... src/Shop.o"
	@echo "... src/Shop.i"
	@echo "... src/Shop.s"
	@echo "... src/Snail.o"
	@echo "... src/Snail.i"
	@echo "... src/Snail.s"
	@echo "... src/Space.o"
	@echo "... src/Space.i"
	@echo "... src/Space.s"
	@echo "... src/TextObject.o"
	@echo "... src/TextObject.i"
	@echo "... src/TextObject.s"
	@echo "... src/Texture.o"
	@echo "... src/Texture.i"
	@echo "... src/Texture.s"
	@echo "... src/TitleScreen.o"
	@echo "... src/TitleScreen.i"
	@echo "... src/TitleScreen.s"
	@echo "... src/Turret.o"
	@echo "... src/Turret.i"
	@echo "... src/Turret.s"
	@echo "... src/Upgrades.o"
	@echo "... src/Upgrades.i"
	@echo "... src/Upgrades.s"
	@echo "... src/Utilities.o"
	@echo "... src/Utilities.i"
	@echo "... src/Utilities.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /mnt/c/Users/Joel/Desktop/Margarita/Margarita/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

